#!/bin/sh

export PRINTERMANAGER_SQLDSN="host=$PRINTERMANAGER_HOST port=$PRINTERMANAGER_PORT user=$PRINTERMANAGER_USER password=$PRINTERMANAGER_PASS dbname=$PRINTERMANAGER_DATABASE sslmode=disable"

exec $1
