// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Building                string
	Group                   string
	GroupUserAssignment     string
	Location                string
	LocationGroupAssignment string
	LocationUserAssignment  string
	Manufacturer            string
	Model                   string
	Printer                 string
	User                    string
}{
	Building:                "building",
	Group:                   "group",
	GroupUserAssignment:     "group_user_assignment",
	Location:                "location",
	LocationGroupAssignment: "location_group_assignment",
	LocationUserAssignment:  "location_user_assignment",
	Manufacturer:            "manufacturer",
	Model:                   "model",
	Printer:                 "printer",
	User:                    "user",
}
