// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Buildings", testBuildingsUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("Locations", testLocationsUpsert)

	t.Run("Manufacturers", testManufacturersUpsert)

	t.Run("Models", testModelsUpsert)

	t.Run("Printers", testPrintersUpsert)

	t.Run("Users", testUsersUpsert)
}
